baseURL = "http://example.org/"
title = "Aeolus d.o.o. Novi Sad"
defaultContentLanguage = "ru"
defaultContentLanguageInSubdir = true
disableHugoGeneratorInject = true
copyright = "Aeolus d.o.o Novi Sad"

[languages]
     [languages.en]
          contentDir = "content/en"
          languageName = "English"
          title = "Aeolus"
          weight = 30 
     [languages.ru] 
          contentDir = "content/ru"
          languageName = "Русский" 
          title = "Aeolus"
          weight = 10
     [languages.sr] 
          contentDir = "content/sr"
          languageName = "Српски"
          title = "Aeolus"
          weight = 20

[markup]
     defaultMarkdownHandler = "goldmark"
     [markup.blackFriday]
          smartDashes = true
          plainIDAnchors = true

     [markup.goldmark]
          [markup.goldmark.parser]
               autoHeadingID = false
