baseURL = "/"
title = "Aeolus d.o.o. Novi Sad"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
disableHugoGeneratorInject = true
copyright = "Aeolus d.o.o Novi Sad"

[languages]
     [languages.en]
          contentDir = "content/en"
          languageName = "English"
          title = "Aeolus"
          weight = 30 
          
          [[languages.en.menu.main]]
                  url = "#about" 
                  name = "About"
                  weight = 200 
          [[languages.en.menu.main]]
                  url = "#services"
                  name = "Services"
                  weight = 250 
          [[languages.en.menu.main]]
                  url = "#advantages"
                  name = "Advantages"
                  weight = 300 
          [[languages.en.menu.main]]
                  url = "#siries"
                  name = "Products"
                  weight = 350 
          [[languages.en.menu.main]]
                  url = "#app"
                  name = "Tillo"
                  weight = 400 

     [languages.ru] 
          contentDir = "content/ru"
          languageName = "Русский" 
          title = "Aeolus"
          weight = 10

          [[languages.ru.menu.main]]
                  url = "#about"
                  name = "О нас"
                  weight = 200 
          [[languages.ru.menu.main]]
                  url = "#services"
                  name = "Сервисы"
                  weight = 250 
          [[languages.ru.menu.main]]
                  url = "#advantages"
                  name = "Наши преимущества"
                  weight = 300 
          [[languages.ru.menu.main]]
                  url = "#siries"
                  name = "Продукты"
                  weight = 350 
          [[languages.ru.menu.main]]
                  url = "#app"
                  name = "Tillo"
                  weight = 400 

     [languages.sr] 
          contentDir = "content/sr"
          languageName = "Српски"
          title = "Aeolus"
          weight = 20
          [[languages.sr.menu.main]]
                  url = "#about"
                  name = "О нама"
                  weight = 200 
          [[languages.sr.menu.main]]
                  url = "#services"
                  name = "Сервиси"
                  weight = 250 
          [[languages.sr.menu.main]]
                  url = "#advantages"
                  name = "Предности"
                  weight = 300 
          [[languages.sr.menu.main]]
                  url = "#siries"
                  name = "Производи"
                  weight = 350 
          [[languages.sr.menu.main]]
                  url = "#app"
                  name = "Tillo"
                  weight = 400 

[markup]
     defaultMarkdownHandler = "goldmark"
     [markup.blackFriday]
          smartDashes = true
          plainIDAnchors = true

     [markup.goldmark]
          [markup.goldmark.parser]
               autoHeadingID = false
