backend:
     name: git-gateway
     branch: master
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
     - label: "Serbian site"
       name: "sr"
       files:
          - label: "Hero Block"
            name: "main"
            file: "content/sr/frontpage/sections/main.md"
            fields:
               - {label: "Садржај", name: "body", widget: "markdown"}
